### ISSUE TITLE
汽车模型是如何制作的

### ISSUE THREAD

**Issue by DusuWen** [CarryKiana/vue-threejs#1]
你好，你的项目对我很有参考意义，请问汽车模型是如何制作的？

**Comment by CarryKiana** [comment]
> 你好，你的项目对我很有参考意义，请问汽车模型是如何制作的？

很高兴能对你有所帮助，three.js对于某些带贴图的模型会渲染错误，估计是模型结构太过复杂，贴图路径解析不正确，网上有针对此情况的设置，但并不总是有效。
项目中的模型是模型网上别人分享的，你可以去模型网、模之屋看看。至于模型制作，这属于3d建模这一大职业了，三言两语讲不清楚。建模软件很多，推荐blender，b站有完整的教程，社区也很友好。另外，建模真的很费力。

**Comment by CarryKiana** [comment]
> 你好，你的项目对我很有参考意义，请问汽车模型是如何制作的？

很高兴能对你有所帮助，three.js对于某些带贴图的模型会渲染错误，估计是模型结构太过复杂，贴图路径解析不正确，网上有针对此情况的设置，但并不总是有效。
项目中的模型是模型网上别人分享的，你可以去模型网、模之屋看看。至于模型制作，这属于3d建模这一大职业了，三言两语讲不清楚。建模软件很多，推荐blender，b站有完整的教程，社区也很友好。另外，建模真的很费力。

**Comment by DusuWen** [comment]
> > 你好，你的项目对我很有参考意义，请问汽车模型是如何制作的？
> 
> 很高兴能对你有所帮助，three.js对于某些带贴图的模型会渲染错误，估计是模型结构太过复杂，贴图路径解析不正确，网上有针对此情况的设置，但并不总是有效。
> 项目中的模型是模型网上别人分享的，你可以去模型网、模之屋看看。至于模型制作，这属于3d建模这一大职业了，三言两语讲不清楚。建模软件很多，推荐blender，b站有完整的教程，社区也很友好。另外，建模真的很费力。

非常感谢
